/*
 * CalculatorAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import io.apimatic.examples.models.*;
import io.apimatic.examples.exceptions.*;
import io.apimatic.examples.APIHelper;
import io.apimatic.examples.Configuration;
import io.apimatic.examples.testing.TestHelper;
import io.apimatic.examples.controllers.SimpleCalculatorController;

import com.fasterxml.jackson.core.type.TypeReference;

public class SimpleCalculatorControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static SimpleCalculatorController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getSimpleCalculator();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * This is a test case of addition.
     * @throws Throwable
     */
    @Test
    public void testSum() throws Throwable {
        // Parameters for the API call
        OperationTypeEnum operation = OperationTypeEnum.fromString("SUM");
        double x = 50d;
        double y = 25d;

        // Set callback and perform API call
        double result = 0;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getCalculate(operation, x, y);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
 
        assertEquals("Response does not match expected value", 
            75, result, ASSERT_PRECISION);
    }

    /**
     * This is a test case of multiplication
     * @throws Throwable
     */
    @Test
    public void testMultiply() throws Throwable {
        // Parameters for the API call
        OperationTypeEnum operation = OperationTypeEnum.fromString("MULTIPLY");
        double x = 10d;
        double y = 2d;

        // Set callback and perform API call
        double result = 0;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getCalculate(operation, x, y);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
 
        assertEquals("Response does not match expected value", 
            20, result, ASSERT_PRECISION);
    }

    /**
     * This is a test case of subtraction
     * @throws Throwable
     */
    @Test
    public void testSubtract() throws Throwable {
        // Parameters for the API call
        OperationTypeEnum operation = OperationTypeEnum.fromString("SUBTRACT");
        double x = 10d;
        double y = 5d;

        // Set callback and perform API call
        double result = 0;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getCalculate(operation, x, y);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
 
        assertEquals("Response does not match expected value", 
            5, result, ASSERT_PRECISION);
    }

    /**
     * This is a test case of division
     * @throws Throwable
     */
    @Test
    public void testDivide() throws Throwable {
        // Parameters for the API call
        OperationTypeEnum operation = OperationTypeEnum.fromString("DIVIDE");
        double x = 20d;
        double y = 10d;

        // Set callback and perform API call
        double result = 0;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getCalculate(operation, x, y);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test whether the captured response is as we expected
        assertNotNull("Result does not exist", 
                result);
 
        assertEquals("Response does not match expected value", 
            2, result, ASSERT_PRECISION);
    }

}
