/*
 * CalculatorAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://examples.apimatic.io/apps/calculator";

}
